### PR TITLE
Changed fmuproxy to fmu-proxy

### LINKED ISSUE #74: FMU Proxy URI is not recognised as a simulator source
OSP Validator does not recognise FMUs with fmu proxy is source. For instance, `<Simulator name="vessel_model" source="fmu-proxy://localhost:9090?guid=b71f76f7-b51e-40d5-affb-f63905622e2b" stepSize="0.05">` gives the following error message:

`Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Unsupported URI schema: 'fmu-proxy' in URI: 'fmu-proxy://localhost:9090?guid=b71f76f7-b51e-40d5-affb-f63905622e2b' . Supported schemas are: [file, fmuproxy]
        at com.opensimulationplatform.systemstructure.util.DefaultOspModelDescriptionLocator.get(DefaultOspModelDescriptionLocator.java:58)
        at com.opensimulationplatform.cli.Validator.getModelDescriptionErrorMessages(Validator.java:93)
        at com.opensimulationplatform.cli.Validator.validate(Validator.java:48)
        at com.opensimulationplatform.cli.Main.main(Main.java:79)
Caused by: java.lang.RuntimeException: Unsupported URI schema: 'fmu-proxy' in URI: 'fmu-proxy://localhost:9090?guid=b71f76f7-b51e-40d5-affb-f63905622e2b' . Supported schemas are: [file, fmuproxy]`

### PR DESCRIPTION
**Pull request by THEvang**
Replaces `fmuproxy` with `fmu-proxy`

closes #74

### CODE REVIEW

**Comment by mrindar** [comment]
Does libcosim expect the schema to be `fmu-proxy` instead of `fmuproxy` now?

**Comment by THEvang** [comment]
I think so. See issue #74 for more info

**Comment by mrindar** [comment]
HOORAY for moving targets! :) This is a critiacl bug that should be hotfixed into master. See [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) under Hotfix Branches.

**Comment by mrindar** [comment]
> There is also a problem with finding FMU proxy FMU's by GUID (issue #76)

I was not made aware that `guid` was a possible schema. I wouldn't say that it is a critical _bug_ though, because we explicitly state that we only support `fmuproxy` and `file` uri schemas. Perhaps you could make an issue stating that we should add support for `guid` uri schemas as well?

**Comment by THEvang** [comment]
> 
> 
> HOORAY for moving targets! :) This is a critiacl bug that should be hotfixed into master. See [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) under Hotfix Branches.

Is it ok if I merge this branch directly to master? 

According to the gitflow workflow hotfix branches should come from master.

**Comment by THEvang** [comment]
I'll do it the proper way instead of being lazy

**Comment by mrindar** [comment]
> 
> 
> > HOORAY for moving targets! :) This is a critiacl bug that should be hotfixed into master. See [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) under Hotfix Branches.
> 
> Is it ok if I merge this branch directly to master?
> 
> According to the gitflow workflow hotfix branches should come from master.

I think it is easiest to just create the hotfix branch from master, and cherry pick this commit. Then edit this PR to merge hotfix branch back into master. After that I'll create new release binaries

**Pull request closed without merging**
